/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

public class App {

    public static void main(String[] args) {
        //proof of life
        Gson gson = new Gson();
        String jsonReturn = gson.toJson(1);
        System.out.println(jsonReturn);
    }
}
